spring:
  application:
    name: undertakes
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.165.2:3306/platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: '123456'
#  rabbitmq:
#    host: 47.98.165.2
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 8056
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
#    configLocation: classpath:mybatis.xml
    configuration:
      map-underscore-to-camel-case: true